---
- name: apache is installed
  hosts: all
  tasks:
  - name: latest apache version installed
    yum:
      name: httpd
      state: latest
  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest
  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started
  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
  - name: apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
