---
- name: try it out
  hosts: all
  become: true
  vars:
    - "{{ DIRECTORY }}"
    - "{{ FILE }}"
    - "{{ CONTENT }}"

  tasks:
    - name: content 
      copy:
        content: "{{ CONTENT }}"
        dest: "{{ DIRECTORY }}/{{FILE}}"
        state: touch
